[ dependencies ]
base = [
  "acpi_call",                     # Thinkpad power management
  "alsa-utils",                    # ALSA CLI control
  "arc-theme",                     # GTK theme
  "bind-tools",                    # DNS utils like dig(1)
  "cronie",                        # Crontab
  "ethtool",                       # Disable Wake On LAN
  "gpsd",                          # get lat,long coordinates
  "guvcview",                      # Webcam application
  "iftop",                         # Network monitor
  "net-tools",                     # Network tooling
  "nautilus",                      # File Manager
  "nodejs-material-design-icons",  # Icon set
  "noto-fonts-emoji",              # Emoji font
  "perf",                          # perf command
  "playerctl",                     # Pulse audio CLI control
  "smartmontools",                 # disk drive health info
  "tlp",                           # Linux power management
  "tp_smapi",                      # Thinkpad power management
  "ttf-freefont",                  # Base unicode symbols
  "wpa_actiond",                   # Auto connect to wifi
  "x86_energy_perf_policy",        # Tune power CPU power saving
  "xbindkeys",                     # Figure out the XF86 names for keys
]

aur = [
  "apvlv",                   # PDF viewer
  "flamegraph-git",          # Tools to generate flamegraphs from perf(1)
  "google-drive-ocamlfuse",  # Google Drive client
  "mininet",                 # Network emulator
  "obs-linuxbrowser",        # OBS Plugin Overlay
  "peek-git",                # Gif recorder
  "perf-tools",              # Scripts to measure performance
  "rofi-dmenu",              # Symlink rofi to dmenu
  "screenkey-git",           # Show keys on screen
  "teiler-git",              # Screenshot / screencast tool
  "tzupdate",                # Auto set timezone
  "wrk"                      # Benchmarking tool
]
